Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakari.Data;
using Bakari.Models;
using System.Diagnostics.Metrics;

namespace Bakari.Controllers
{
    public class ItemsController : Controller
    {
        private readonly BakariContext _context;

        public ItemsController(BakariContext context)
        {
            _context = context;
        }
        // GET: Items/Create
        public IActionResult Add()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("ItemId,CategoryId,ItemCode,ItemName,Description,ItemPrice,ImagePath")] Item item)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
            }
            if (await CreateStockAsync(item))
            {
                return RedirectToAction(nameof(Salelist));
            }


            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", item.CategoryId);
            return View(item);
        }
        //Creates stock of new itne
        public async Task<bool> CreateStockAsync (Item item)
        {
            if (item == null)
            {
                return false;
            }

            var cat = await _context.Category.FindAsync(item.CategoryId);
            if (cat == null)
            {
                return false;
            }
            Stock stock = new()
            {
                    ItemId=item.ItemId,
                   ItemName = item.ItemName,
                   Category = cat.CategoryName,
                   Quantity = 0,
                   CostPrice = 0,
                   Total = 0,
                   SalePrice=item.ItemPrice,
                   Item=item,
                   LastUpDated = DateTime.UtcNow


            };

               if (!ModelState.IsValid)
               {
                   _context.Add(stock);
                   await _context.SaveChangesAsync();

                return true;

               }
            return false;

        }
        // GET: Sale
        public async Task<IActionResult> Salelist(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Category" ? "cat_desc" : "Category";
            ViewData["CurrentFilter"] = searchString;


            var items = from s in _context.Item.Include(p => p.Category)
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.ItemName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    items = items.OrderByDescending(s => s.ItemName);
                    break;
                case "cat_desc":
                    items = items.OrderByDescending(s => s.Category.CategoryName);
                    break;

                default:
                    items= items.OrderByDescending(s => s.ItemPrice);
                    break;
            }


            return View(await items.ToListAsync());
        }

        //Add to Basket
        public async Task<IActionResult> AddtoBasket(int? id)
            {
                if (id == null || _context.Item == null)
                {
                    return NotFound();
                }
            //Basket basket;
                var item = await _context.Item
                    .Include(i => i.Category)
                    .FirstOrDefaultAsync(m => m.ItemId == id);
                if (item != null)
                {


                    /*if (Viewdata["CartCounter"] != null)
                    {
                        _carts = ViewData["CartCounter"] as List<Cart>;
                    }
                    */
                //counter++;
                //Get list of items in basket
                var BasketItems = _context.Basket.ToList();
                    if (BasketItems.Any(model => model.ItemId == id))
                    {
                        var basket = BasketItems.Single(model => model.ItemId == id);
                        basket.Quantity++;
                        basket.TotalPrice = basket.UnitPrice * basket.Quantity;

                        if (ModelState.IsValid)
                        {
                            try
                            {
                                _context.Update(basket);
                                await _context.SaveChangesAsync();
                            }
                            catch (DbUpdateConcurrencyException)
                            {
                                throw;
                            }

                        }
                    }
                    //new item added to bask
                    else
                    {
                        Basket basket = new()
                        {
                            ItemId = item.ItemId,
                            ImagePath = item.ImagePath,
                            UnitPrice = item.ItemPrice,
                            Quantity = 1,
                            TotalPrice = item.ItemPrice,
                            Item = item
                        };
                  
                        if (ModelState.IsValid)
                        {
                            _context.Add(basket);
                            await _context.SaveChangesAsync();

                        }
                        //_carts.Add(cart);

                    }
                    //Counter++;
                    //ViewData["BasketCounter"] = counter;
                    //ViewData["Cart"] = _carts;

                    return RedirectToAction(nameof(Salelist));
                }
                else
                {
                    return NotFound();
                }
            }

        // GET: Products
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;


            var products = from s in _context.Item.Include(p => p.Category)
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.ItemName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(s => s.ItemName);
                    break;


                default:
                    products = products.OrderBy(s => s.ItemName);
                    break;
            }


            return View(await products.ToListAsync());
        }


        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var item = await _context.Item
                    .Include(i => i.Category)
                    .FirstOrDefaultAsync(m => m.ItemId == id);
                if (item == null)
                {
                    return NotFound();
                }

                return View(item);
            }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,CategoryId,ItemCode,ItemName,Description,ProductPrice,ImagePath")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                //create stock
                Stock stock = new()
                {

                        ItemId= item.ItemId,
                        ItemName = item.ItemName,
                        Category=item.Category.CategoryName,
                        Quantity = 0,
                        CostPrice = 0,
                        Total = 0,
                        SalePrice=item.ItemPrice,
                        Item=item,
                        LastUpDated=DateTime.UtcNow
                   

                };

                if (ModelState.IsValid)
                {
                    _context.Add(stock);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
               
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", item.CategoryId);
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);

Controllers/StocksController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakari.Data;
using Bakari.Models;
using Microsoft.Data.SqlClient;
using Bakari.Migrations;
using Stock = Bakari.Models.Stock;

namespace Bakari.Controllers
{
    public class StocksController : Controller
    {
        private readonly BakariContext _context;

        public StocksController(BakariContext context)
        {
            _context = context;
        }

        // GET: Stocks
        public async Task<IActionResult> Stocklist(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Category" ? "cat_desc" : "Category";
            ViewData["CurrentFilter"] = searchString;


            var stocks = from s in _context.Stock.Include(p => p.Item)
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                stocks = stocks.Where(s => s.ItemName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    stocks = stocks.OrderByDescending(s => s.ItemName);
                    break;
                case "cat_desc":
                    stocks = stocks.OrderByDescending(s => s.Category);
                    break;

                default:
                    stocks = stocks.OrderByDescending(s => s.LastUpDated);
                    break;
            }


            return View(await stocks.ToListAsync());
        }

       

        // GET: Stocks
        public async Task<IActionResult> Index()
        {
            var bakariContext = _context.Stock;
            return View(await bakariContext.ToListAsync());
        }

        // GET: Stocks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stock
                .Include(p => p.Item)
                .FirstOrDefaultAsync(m => m.StockId == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // GET: Stocks/Create
        public IActionResult Create()
        {
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemName");
            return View();
        }

        // POST: Stocks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StockId,ItemId,Quantity,CostPrice,Total,ImagePath")] Stock stock)
        {
            if (ModelState.IsValid)
            {
                _context.Add(stock);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemId"] = new SelectList(_context.Category, "ItemId", "ItemName", stock.ItemId);
            return View(stock);
        }
        // GET: Stocks/Update/5
        public async Task<IActionResult> Update(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stock.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemName");
            return View(stock);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(int id, [Bind("StockId,ItemId,Quantity,Category,ItemName,CostPrice,Total,ImagePath")] Stock stock)
        {
            if (id != stock.StockId)
            {
                return NotFound();
            }
            stock.LastUpDated = DateTime.Now;
            if (!ModelState.IsValid)
            {
                try
                {
                    _context.Update(stock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockExists(stock.StockId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Stocklist));
            }
            ViewData["ItemId"] = new SelectList(_context.Category, "ItemId", "ItemName", stock.ItemId);
            return View(stock);
        }

        // GET: Stocks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stock.FindAsync(id);
            if (stock == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemName");
            return View(stock);
        }
       

        // POST: Stocks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StockId,ItemId,Quantity,CostPrice,Total,ImagePath")] Stock stock)
        {
            if (id != stock.StockId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(stock);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StockExists(stock.StockId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemId"] = new SelectList(_context.Category, "ItemId", "ItemName", stock.ItemId);
            return View(stock);
        }

        // GET: Stocks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var stock = await _context.Stock
                .Include(s => s.Item)
                .FirstOrDefaultAsync(m => m.StockId == id);
            if (stock == null)
            {
                return NotFound();
            }

            return View(stock);
        }

        // POST: Stocks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var stock = await _context.Stock.FindAsync(id);
            if (stock != null)
            {
                _context.Stock.Remove(stock);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StockExists(int id)
        {
            return _context.Stock.Any(e => e.StockId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bakari</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Bakari.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" />

    <!-- Bootstrap Font Icon CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Bakari</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Item Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Items" asp-action="Salelist">Sale</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stocks" asp-action="Stocklist">Inventory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Orders" asp-action="OrderList">Orders</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transanctions" asp-action="Wallet">Wallet</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reports" asp-action="Index">Reports</a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav flex-grow-1 navbar-right">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Baskets" asp-action="BasketList">
                            <i class="fa fa-shopping-basket" aria-hidden="true"></i><span> Basket</span>
                        </a>

                    </li>
                </ul>
            </div>
        
    </header>
    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Bakari - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_Layout1.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dashboar Bakari </title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="assets/css/bootstrap.css">

    <link rel="stylesheet" href="assets/vendors/iconly/bold.css">

    <link rel="stylesheet" href="assets/vendors/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="assets/vendors/bootstrap-icons/bootstrap-icons.css">
    <link rel="stylesheet" href="assets/css/app.css">
    <link rel="shortcut icon" href="assets/images/favicon.svg" type="image/x-icon">
</head>

<body>
    <div id="app">
        <div id="sidebar" class="active">
            <div class="sidebar-wrapper active">
                <div class="sidebar-header">
                    <div class="d-flex justify-content-between">
                        <div class="logo">
                            <a href=""><img src="assets/images/logo/logo1.png" alt="Logo" srcset=""></a>
                        </div>
                        <div class="toggler">
                            <a href="#" class="sidebar-hide d-xl-none d-block"><i class="bi bi-x bi-middle"></i></a>
                        </div>
                    </div>
                </div>
                <div class="sidebar-menu">
                    <ul class="menu">
                        <li class="sidebar-title">Menu</li>

                        <li class="sidebar-item active ">
                            <a asp-controller="Home" asp-action="Index" class='sidebar-link'>
                                <i class="bi bi-house-fill"></i>
                                <span>Dashboard</span>
                            </a>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="bi bi-cart"></i>
                                <span>Sale</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    <a asp-controller="Items" asp-action="Index">Sale Items</a>
                                </li>
                                <li class="submenu-item ">
                                    <a asp-controller="Baskets" asp-action="Index">Basket</a>
                                </li>
                                <li class="submenu-item ">
                                    <a asp-controller="Orders" asp-action="Index">Orders</a>
                                </li>
                              
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="bi bi-signpost-2"></i>
                                <span>Item Categories</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    <a asp-controller="Categories" asp-action="Add">Add Category</a>
                                </li>
                                <li class="submenu-item ">
                                    <a asp-controller="Categories" asp-action="Index">Categories</a>
                                </li>
                              
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="bi bi-cart4"></i>
                                <span>Items</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    <a asp-controller="Items" asp-action="Index">Sale Items</a>
                                </li>
                                <li class="submenu-item ">
                                    <a asp-controller="Items" asp-action="Create">Add  Item</a>
                                </li>
                                <li class="submenu-item ">
                                    <a href="component-badge.html">Stock</a>
                                </li>
                              
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="bi bi-card-checklist"></i>
                                <span>Inventory</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    <a href="component-alert.html">List</a>
                                </li>
                                <li class="submenu-item ">
                                    <a href="component-badge.html">Update</a>
                                </li>
                              
                            </ul>
                        </li>
                        <li class="sidebar-item  has-sub">
                            <a href="#" class='sidebar-link'>
                                <i class="bi bi-graph-up"></i>
                                <span>Transanctions</span>
                            </a>
                            <ul class="submenu ">
                                <li class="submenu-item ">
                                    <a href="component-alert.html">Add Category</a>
                                </li>
                                <li class="submenu-item ">
                                    <a href="component-badge.html">Transact</a>
                                </li>
                              
                            </ul>
                        </li>


                        <li class="sidebar-item active ">
                            <a href="index.html" class='sidebar-link'>
                                <i class="bi bi-house-x"></i>
                                <span>Sign Out</span>
                            </a>
                        </li>
                      



                    </ul>
                </div>
                <button class="sidebar-toggler btn x"><i data-feather="x"></i></button>
            </div>
        </div>
        <div id="main">
            <header class="mb-3">
                <a href="#" class="burger-btn d-block d-xl-none">
                    <i class="bi bi-justify fs-3"></i>
                </a>
            </header>
            <div class="container">
                <main role="main" class="pb-3">
                    @RenderBody()
                </main>
            </div>
         

            <footer>
                <div class="footer clearfix mb-0 text-muted">
                    <div class="float-start">
                        <p>2024 &copy; Bakari</p>
                    </div>
                    <div class="float-end">
                        <p>
                            Product of <span class="text-primary"></span> by <a href="http://flipflop.ug">Flip Flop Technologies</a>
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="assets/vendors/perfect-scrollbar/perfect-scrollbar.min.js"></script>
    <script src="assets/js/bootstrap.bundle.min.js"></script>

    <script src="assets/vendors/apexcharts/apexcharts.js"></script>
    <script src="assets/js/pages/dashboard.js"></script>

    <script src="assets/js/main.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>