Models/Basket.cs
using System.ComponentModel.DataAnnotations;

namespace Bakari.Models
{
    public class Basket
    {
        public int BasketId { get; set; }

        public int ItemId { get; set; }

        [DisplayFormat(DataFormatString = "{0: #,#}", ApplyFormatInEditMode = true)]
        public decimal Quantity { get; set; }
        [DisplayFormat(DataFormatString = "{0: #,#}", ApplyFormatInEditMode = true)]
        public decimal UnitPrice { get; set; }

        [DisplayFormat(DataFormatString = "{0: #,#}", ApplyFormatInEditMode = true)]
        public decimal TotalPrice { get; set; }

        public string? ImagePath { get; set; }


        public required Item Item { get; set; }
        public virtual ICollection<Basket>? Baskets { get; set; }
        [DisplayFormat(DataFormatString = "{0: #,#}", ApplyFormatInEditMode = true)]
        public decimal? TotalBasket
        {


            get
            {
                if (Baskets == null) { return 0; }
                return Baskets.Sum(x => x.TotalPrice);
            }

        }
    }
}

Controllers/BasketsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakari.Data;
using Bakari.Models;
using Microsoft.IdentityModel.Tokens;
using Bakari.Migrations;

namespace Bakari.Controllers
{
    public class BasketsController : Controller
    {
        private readonly BakariContext _context;

        public BasketsController(BakariContext context)
        {
            _context = context;
        }
        public IActionResult EmptyBasket()
        {
            return View();
        }

        // GET: Baskets
        public async Task<IActionResult> Index()
        {
            if (_context.Basket.IsNullOrEmpty())
            {
                return RedirectToAction(nameof(EmptyBasket));
            }
            var glamManageContext = _context.Basket.Include(b =>b.Item);
            return View(await glamManageContext.ToListAsync());
        }

        public async Task<IActionResult> BasketList()
        {
            if (_context.Basket.IsNullOrEmpty())
            {
                return RedirectToAction(nameof(EmptyBasket));
            }
            
            var bakariContext = _context.Basket.Include(b => b.Item);
            ViewData["baskettotal"] = bakariContext.Sum(t=>t.TotalPrice);
            return View(await bakariContext.ToListAsync());
        }
        public async Task<IActionResult> Remove(int? id)
        {
            if (id == null || _context.Basket == null)
            {
                return NotFound();
            }

            var basket = await _context.Basket
                .Include(b => b.Item)
                .FirstOrDefaultAsync(m => m.BasketId == id);

            if (basket != null)
            {
                _context.Basket.Remove(basket);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(BasketList));


        }
        public async Task<IActionResult> Increase(int? id)
        {
            if (id == null || _context.Basket == null)
            {
                return NotFound();
            }

            var basket = await _context.Basket
                .Include(b => b.Item)
                .FirstOrDefaultAsync(m => m.BasketId == id);

            if (basket != null)
            {
                basket.Quantity++;
                basket.TotalPrice = basket.Quantity * basket.UnitPrice;
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Basket.Update(basket);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!BasketExists(basket.BasketId))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                }
            }
          


            return RedirectToAction(nameof(BasketList));


        }

        public async Task<IActionResult> Reduce(int? id)
        {
            if (id == null || _context.Basket == null)
            {
                return NotFound();
            }

            var basket
                = await _context.Basket
                .Include(b => b.Item)
                .FirstOrDefaultAsync(m => m.BasketId == id);

            if (basket != null)
            {
                basket.Quantity--;
                basket.TotalPrice = basket.Quantity *basket.UnitPrice;
                if (basket.Quantity < 1)
                {
                    _context.Basket.Remove(basket);
                    await _context.SaveChangesAsync();
                }
                else
                {
                    if (ModelState.IsValid)
                    {
                        try
                        {
                            _context.Update(basket);
                            await _context.SaveChangesAsync();
                        }
                        catch (DbUpdateConcurrencyException)
                        {
                            if (!BasketExists(basket.BasketId))
                            {
                                return NotFound();
                            }
                            else
                            {
                                throw;
                            }
                        }
                    }

                }
            }


            return RedirectToAction(nameof(BasketList));


        }





        // GET: Baskets/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var basket = await _context.Basket
                .Include(b => b.Item)
                .FirstOrDefaultAsync(m => m.BasketId == id);
            if (basket == null)
            {
                return NotFound();
            }

            return View(basket);
        }

        // GET: Baskets/Create
        public IActionResult Create()
        {
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId");
            return View();
        }

        // POST: Baskets/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BasketId,ItemId,Quantity,UnitPrice,TotalPrice,ImagePath")] Basket basket)
        {
            if (ModelState.IsValid)
            {
                _context.Add(basket);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", basket.ItemId);
            return View(basket);
        }

        // GET: Baskets/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var basket = await _context.Basket.FindAsync(id);
            if (basket == null)
            {
                return NotFound();
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", basket.ItemId);
            return View(basket);
        }

        // POST: Baskets/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("BasketId,ItemId,Quantity,UnitPrice,TotalPrice,ImagePath")] Basket basket)
        {
            if (id != basket.BasketId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(basket);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BasketExists(basket.BasketId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["ItemId"] = new SelectList(_context.Item, "ItemId", "ItemId", basket.ItemId);
            return View(basket);
        }

        // GET: Baskets/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var basket = await _context.Basket
                .Include(b => b.Item)
                .FirstOrDefaultAsync(m => m.BasketId == id);
            if (basket == null)
            {
                return NotFound();
            }

            return View(basket);
        }

        // POST: Baskets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var basket = await _context.Basket.FindAsync(id);
            if (basket != null)
            {
                _context.Basket.Remove(basket);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BasketExists(int id)
        {
            return _context.Basket.Any(e => e.BasketId == id);
        }
        public async Task<IActionResult> CheckOut()
        {
            if (_context.Basket.IsNullOrEmpty())
            {
                return RedirectToAction("Salelist", "Items");
            }
            
            if (await CompareStockAsync())
            {
                if (await ReduceStockAsync())
                {
                    //create order
                    var order = new Order();

                    order = await CreateOrder<Order>(TotalBasket());
                    if (order != null)
                    {
                        if (await AddOrderDetail<bool>(order))
                        {
                            //Clear Shopping Basket
                            await ClearBasketAsync();
                            //add transaction
                            await AddTransanctionAsync(order);
                            return RedirectToAction("OrderList", "Orders");
                        }
                    }

Views/Baskets/BasketList.cshtml
@model IEnumerable<Bakari.Models.Basket>

@{
    ViewData["Title"] = "Index";

}

<h1>TOTAL BILL</h1>
<h3 style="background:blue">UGX @ViewBag.baskettotal.ToString(format: "#,##0")</h3>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
          
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Item.ItemName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UnitPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.TotalPrice)
                </td>
                
                <td>
                    <a class="fa fa-chevron-circle-up" asp-route-id="@item.BasketId" asp-controller="Baskets" asp-action="Increase">    </a> 
                    <a class="fa fa-trash-o" aria-hidden="true" asp-route-id="@item.BasketId" asp-controller="Baskets" asp-action="Remove">    </a> 
                    <a class="fa fa-chevron-circle-down" aria-hidden="true" asp-route-id="@item.BasketId" asp-controller="Baskets" asp-action="Reduce"> </a>
                </td>
        </tr>
}       
        <tr>
            <td> </td>
            <td> </td>
            <td> </td>
            <td>
              
            </td>
            <td>
                <form asp-action="CheckOut" >
                    <input type="submit" value="Check Out" class="btn btn-primary rounded-pill px-3" />
                </form>
            </td>
        </tr>
    </tbody>
</table>

Views/Baskets/Create.cshtml
@model Bakari.Models.Basket

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Basket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ItemId" class="control-label"></label>
                <select asp-for="ItemId" class ="form-control" asp-items="ViewBag.ItemId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Baskets/Delete.cshtml
@model Bakari.Models.Basket

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Basket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.ItemId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BasketId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Baskets/Details.cshtml
@model Bakari.Models.Basket

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Basket</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UnitPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UnitPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImagePath)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Item)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Item.ItemId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.BasketId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Baskets/Edit.cshtml
@model Bakari.Models.Basket

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Basket</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BasketId" />
            <div class="form-group">
                <label asp-for="ItemId" class="control-label"></label>
                <select asp-for="ItemId" class="form-control" asp-items="ViewBag.ItemId"></select>
                <span asp-validation-for="ItemId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UnitPrice" class="control-label"></label>
                <input asp-for="UnitPrice" class="form-control" />
                <span asp-validation-for="UnitPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TotalPrice" class="control-label"></label>
                <input asp-for="TotalPrice" class="form-control" />
                <span asp-validation-for="TotalPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImagePath" class="control-label"></label>
                <input asp-for="ImagePath" class="form-control" />
                <span asp-validation-for="ImagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Baskets/EmptyBasket.cshtml
@model IEnumerable<Bakari.Models.Basket>

@{
    ViewData["Title"] = "Empty";
}

<h1>Oops the basket is empty!!</h1>

<p>
   
    <form asp-controller="Items" asp-action="SaleList" >
        <input type="submit" value="Add to Basket" class="btn btn-primary rounded-pill px-3" />
    </form>
</p>

Views/Baskets/Index.cshtml
@model IEnumerable<Bakari.Models.Basket>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UnitPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TotalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ImagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Item)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UnitPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TotalPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ImagePath)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Item.ItemId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.BasketId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.BasketId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.BasketId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>