Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakari.Data;
using Bakari.Models;

namespace Bakari.Controllers
{
    public class CategoriesController : Controller
    {
        private readonly BakariContext _context;

        public CategoriesController(BakariContext context)
        {
            _context = context;
        }

        // GET: Categories
        public async Task<IActionResult> Index()
        {
            return View(await _context.Category.ToListAsync());
        }

        // GET: Categories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        // GET: Categories/Create
        public IActionResult Add()
        {
            return View();
        }
        // POST: Categories/Add
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("CategoryId,CategoryCode,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryCode,CategoryName")] Category category)
        {
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CategoryId,CategoryCode,CategoryName")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Categories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Category
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Category.FindAsync(id);
            if (category != null)
            {
                _context.Category.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Category.Any(e => e.CategoryId == id);
        }
    }
}

Controllers/HomeController.cs
using Bakari.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Bakari.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bakari.Data;
using Bakari.Models;
using System.Diagnostics.Metrics;

namespace Bakari.Controllers
{
    public class ItemsController : Controller
    {
        private readonly BakariContext _context;

        public ItemsController(BakariContext context)
        {
            _context = context;
        }
        // GET: Items/Create
        public IActionResult Add()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add([Bind("ItemId,CategoryId,ItemCode,ItemName,Description,ItemPrice,ImagePath")] Item item)
        {
            if (!ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
            }
            if (await CreateStockAsync(item))
            {
                return RedirectToAction(nameof(Salelist));
            }


            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName", item.CategoryId);
            return View(item);
        }
        //Creates stock of new itne
        public async Task<bool> CreateStockAsync (Item item)
        {
            if (item == null)
            {
                return false;
            }

            var cat = await _context.Category.FindAsync(item.CategoryId);
            if (cat == null)
            {
                return false;
            }
            Stock stock = new()
            {
                    ItemId=item.ItemId,
                   ItemName = item.ItemName,
                   Category = cat.CategoryName,
                   Quantity = 0,
                   CostPrice = 0,
                   Total = 0,
                   SalePrice=item.ItemPrice,
                   Item=item,
                   LastUpDated = DateTime.UtcNow


            };

               if (!ModelState.IsValid)
               {
                   _context.Add(stock);
                   await _context.SaveChangesAsync();

                return true;

               }
            return false;

        }
        // GET: Sale
        public async Task<IActionResult> Salelist(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Category" ? "cat_desc" : "Category";
            ViewData["CurrentFilter"] = searchString;


            var items = from s in _context.Item.Include(p => p.Category)
                         select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                items = items.Where(s => s.ItemName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    items = items.OrderByDescending(s => s.ItemName);
                    break;
                case "cat_desc":
                    items = items.OrderByDescending(s => s.Category.CategoryName);
                    break;

                default:
                    items= items.OrderByDescending(s => s.ItemPrice);
                    break;
            }


            return View(await items.ToListAsync());
        }

        //Add to Basket
        public async Task<IActionResult> AddtoBasket(int? id)
            {
                if (id == null || _context.Item == null)
                {
                    return NotFound();
                }
            //Basket basket;
                var item = await _context.Item
                    .Include(i => i.Category)
                    .FirstOrDefaultAsync(m => m.ItemId == id);
                if (item != null)
                {


                    /*if (Viewdata["CartCounter"] != null)
                    {
                        _carts = ViewData["CartCounter"] as List<Cart>;
                    }
                    */
                //counter++;
                //Get list of items in basket
                var BasketItems = _context.Basket.ToList();
                    if (BasketItems.Any(model => model.ItemId == id))
                    {
                        var basket = BasketItems.Single(model => model.ItemId == id);
                        basket.Quantity++;
                        basket.TotalPrice = basket.UnitPrice * basket.Quantity;

                        if (ModelState.IsValid)
                        {
                            try
                            {
                                _context.Update(basket);
                                await _context.SaveChangesAsync();
                            }
                            catch (DbUpdateConcurrencyException)
                            {
                                throw;
                            }

                        }
                    }
                    //new item added to bask
                    else
                    {
                        Basket basket = new()
                        {
                            ItemId = item.ItemId,
                            ImagePath = item.ImagePath,
                            UnitPrice = item.ItemPrice,
                            Quantity = 1,
                            TotalPrice = item.ItemPrice,
                            Item = item
                        };
                  
                        if (ModelState.IsValid)
                        {
                            _context.Add(basket);
                            await _context.SaveChangesAsync();

                        }
                        //_carts.Add(cart);

                    }
                    //Counter++;
                    //ViewData["BasketCounter"] = counter;
                    //ViewData["Cart"] = _carts;

                    return RedirectToAction(nameof(Salelist));
                }
                else
                {
                    return NotFound();
                }
            }

        // GET: Products
        public async Task<IActionResult> Index(string searchString, string sortOrder)
        {
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["CurrentFilter"] = searchString;


            var products = from s in _context.Item.Include(p => p.Category)
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                products = products.Where(s => s.ItemName.Contains(searchString));
            }
            switch (sortOrder)
            {
                case "name_desc":
                    products = products.OrderByDescending(s => s.ItemName);
                    break;


                default:
                    products = products.OrderBy(s => s.ItemName);
                    break;
            }


            return View(await products.ToListAsync());
        }


        // GET: Items/Details/5
        public async Task<IActionResult> Details(int? id)
            {
                if (id == null)
                {
                    return NotFound();
                }

                var item = await _context.Item
                    .Include(i => i.Category)
                    .FirstOrDefaultAsync(m => m.ItemId == id);
                if (item == null)
                {
                    return NotFound();
                }

                return View(item);
            }

        // GET: Items/Create
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryName");
            return View();
        }

        // POST: Items/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ItemId,CategoryId,ItemCode,ItemName,Description,ProductPrice,ImagePath")] Item item)
        {
            if (ModelState.IsValid)
            {
                _context.Add(item);
                await _context.SaveChangesAsync();
                //create stock
                Stock stock = new()
                {

                        ItemId= item.ItemId,
                        ItemName = item.ItemName,
                        Category=item.Category.CategoryName,
                        Quantity = 0,
                        CostPrice = 0,
                        Total = 0,
                        SalePrice=item.ItemPrice,
                        Item=item,
                        LastUpDated=DateTime.UtcNow
                   

                };

                if (ModelState.IsValid)
                {
                    _context.Add(stock);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
               
            }
            ViewData["CategoryId"] = new SelectList(_context.Category, "CategoryId", "CategoryId", item.CategoryId);
            return View(item);
        }

        // GET: Items/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var item = await _context.Item.FindAsync(id);

Views/Home/Index-old.cshtml
@{
    ViewData["Title"] = "Home Page";
}


<div class="card text-center">
    <div class="card-header">
        <h1>Welcome </h1>
    </div>
    <div class="card-body">
        <h3 class="card-title"> BAKARI</h3>
        <p class="card-text">Your Professional Sales Information Manager.</p>
        <a   asp-action="Sale" asp-controller="Items" class="btn btn-primary">Let's Start</a>
    </div>

</div>

<div class='row mb-5'>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card border-primary mb-3">
            <div class="card-header">
                <i class="bi bi-archive"> Categories</i>
            </div>
            <div class="card-body text-primary">
                <a asp-action="Index" asp-controller="Categories" class="btn btn-primary"> <h5 class="card-title">Item Categories</h5></a>
                
            </div>
            
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card border-primary mb-3">
            <div class="card-header">
                <i class="bi-clipboard-data"> Items</i>
            </div>
            <div class="card-body text-primary">
                <h5 class="card-title">Products & Sales</h5>
                <p class="card-text">Select sale items and add to shopping basket .</p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card border-primary mb-3">
            <div class="card-header">
                <i class="bi bi-basket"> Basket</i>
            </div>
            <div class="card-body text-primary">
                <h5 class="card-title"> Sales Items for Ordering</h5>
                <p class="card-text"> Verify items in shopping cart and complete order.</p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-4">
        <div class="card border-primary mb-3">
            <div class="card-header">
                <i class="bi-basket"> Orders</i>
            </div>
            <div class="card-body text-primary">
                <h5 class="card-title">Patient Biometrics</h5>
                <p class="card-text">Patient records, addresses, contacts and special needs.  </p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card border-primary mb-3">
            <div class="card-header">
                <i class="bi-files"> Transactions</i>
            </div>
            <div class="card-body text-primary">
                <h5 class="card-title">Medical Records</h5>
                <p class="card-text">A set of organised past patient medical history .</p>
            </div>
        </div>
    </div>
    <div class="col-sm-4">
        <div class="card border-primary mb-3">
            <div class="card-header">
                <i class="bi bi-receipt"> Reports</i>
            </div>
            <div class="card-body text-primary">
                <h5 class="card-title">Payments & Receipts</h5>
                <p class="card-text">Payments,Receipts, daily transancitons including financial reporting in one place.</p>
            </div>
        </div>
    </div>
</div>
<div class='row mb-5'>
</div>
<div class='row mb-5'>
</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="page-heading">
    <h3>Business Statistics</h3>
</div>
<section id="groups">
    <div class="row match-height">
        <div class="col-12 mt-3 mb-1">
            <h4 class="section-title text-uppercase">This Month</h4>
        </div>
    </div>
    <div class="row match-height">
        <div class="col-12">
            <div class="card-group">
                <div class="card">
                    <div class="card-content">
                        <img class="card-img-top img-fluid" src="assets/images/samples/E.png" alt="Card image cap">
                        <div class="card-body">
                            <h4 class="card-title">Wallet</h4>
                            <p class="card-text">
                                UGX 947,800
                            </p>
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <img class="card-img-top img-fluid" src="assets/images/samples/D.png" alt="Card image cap">
                        <div class="card-body">
                            <h4 class="card-title">Sales Orders</h4>
                            <p class="card-text">
                                236.
                            </p>
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <img class="card-img-top img-fluid" src="assets/images/samples/A.png" alt="Card image cap">
                        <div class="card-body">
                            <h4 class="card-title">Transanctions</h4>
                            <p class="card-text">
                                232.
                            </p>
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
                <div class="card">
                    <div class="card-content">
                        <img class="card-img-top img-fluid" src="assets/images/samples/B.png" alt="Card image cap">
                        <div class="card-body">
                            <h4 class="card-title">Total Inventory</h4>
                            <p class="card-text">
                               UGX 11,000,000
                            </p>
                            <small class="text-muted"></small>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="row match-height">
    <div class="col-12 mt-3 mb-1">
        <h4 class="section-title text-uppercase"></h4>
    </div>
</div>
<div class="page-content">
    <section class="row">

        <div class="col-12 col-lg-9">

            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header">
                            <h4>Monthly Orders</h4>
                        </div>
                        <div class="card-body">
                            <div id="chart-profile-visit"></div>
                        </div>
                    </div>
                </div>
            </div>
           
        </div>
    </section>
</div>